import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logo from "../components/Logo";
import { NavbarDemo } from "@src/components/navbar";
import { NavigationMenuDemo } from "@src/components/navigation-menu";

import Button from "@src/components/button"; // Your Button component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PeUnique",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center p-4 mb-10">
          <Logo />
           <NavigationMenuDemo />
           <Button href="/signup">Sign Up</Button>
        </header>
        <main>{children}</main>
        <footer>Copyright by The PeUnique</footer>
      </body>
    </html>
  );
}
